// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/list-projects.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/data.ts
var SITE_URL = "https://bohdanrohulskyi.com";
var PROJECTS = [
  { title: "Dylan Bachelet", client: "Imagine Magazine", category: "Editorial", filterGroup: "Fashion", url: "/work/dylan-bachelet", vimeoId: "1107691277" },
  { title: "Yaroslava Mohushih", client: "PUMA", category: "Documentary Film", filterGroup: "Commercial", url: "/work/yaroslava-mohushih", vimeoId: "1010047613" },
  { title: "Orserio", client: "Orserio", category: "E-Commerce Brand Film", filterGroup: "Commercial", url: "/work/orserio", vimeoId: "1172857771" },
  { title: "Valentin Day", client: "Zielinski & Rozen", category: "Documentary Campaign Film", filterGroup: "Commercial", url: "/work/valentin-day", vimeoId: "1166656782" },
  { title: "AnOther Magazine", client: "Simone Rocha", category: "Editorial", filterGroup: "Fashion", url: "/work/another-magazine", vimeoId: "1010017917" },
  { title: "Hozier \u2014 Francesca", client: "Hozier", category: "Music Video", filterGroup: "Music Video", url: "/work/hozier-francesca", youtubeId: "K1u_hL11auM" },
  { title: "PUMA FIT 23", client: "PUMA", category: "Commercial / Sport", filterGroup: "Commercial", url: "/work/puma-fit-23", vimeoId: "948342341" },
  { title: "Puma CR", client: "PUMA", category: "Commercial / Sport", filterGroup: "Commercial", url: "/work/puma-cr", vimeoId: "1010036272" },
  { title: "Chernaya \u2014 Rami Kallas", client: "Rami Kallas", category: "Music Video", filterGroup: "Music Video", url: "/work/chernaya-rami-kallas", vimeoId: "1010028819" },
  { title: "The Best of BoF 500 2023", client: "The Business of Fashion", category: "Fashion Recap", filterGroup: "Documentary", url: "/work/bof-500-2023", youtubeId: "zNdnPu8L9_Y" },
  { title: "Alessandro Michele \u2014 The BoF Podcast", client: "The Business of Fashion", category: "Interview / Fashion", filterGroup: "Documentary", url: "/work/alessandro-michele-bof", youtubeId: "qtJqYEtbrBA" },
  { title: "TVORCHI \u2014 \u0412\u0456\u0447-\u043D\u0430-\u0412\u0456\u0447", client: "TVORCHI", category: "Music Video", filterGroup: "Music Video", url: "/work/tvorchi-vich-na-vich", youtubeId: "Y5QMUv7H0ic" },
  { title: "Kotex: Art's Missing Period", client: "Kotex", category: "Documentary Film", filterGroup: "Documentary", url: "/work/kotex-arts-missing-period", youtubeId: "EmCZ8EqEVKE" },
  { title: "Uncharted: Sail GP", client: "Sail GP", category: "Documentary Film", filterGroup: "Documentary", url: "/work/uncharted-sail-gp", youtubeId: "PDfaMsRMGY8" },
  { title: "Moove \u2014 Fire", client: "Moove", category: "Music Video", filterGroup: "Music Video", url: "/work/moove-fire", vimeoId: "1179879918" },
  { title: "Vogue Mexico \u2014 Michelle Salas / Dolce & Gabbana", client: "Vogue Mexico", category: "Documentary", filterGroup: "Documentary", url: "/work/vogue-mexico", youtubeId: "Nh1ZWDz44no" }
];
var CATEGORIES = ["Fashion", "Commercial", "Documentary", "Music Video"];
var CONTACT = {
  name: "Bohdan Rohulskyi",
  role: "Director of Photography (Cinematographer)",
  location: "London, United Kingdom",
  availability: "Available across the UK and Europe",
  email: "rogulskiproject@gmail.com",
  website: SITE_URL
};
var BIO = `Bohdan Rohulskyi is a London-based Director of Photography working across sport, fashion, culture and branded storytelling. With a background in documentary and performance-led work, he creates cinematic imagery rooted in real human presence, textured realism and emotional precision. A strong visual partner for directors and a reliable, production-aware DoP for producers. Own kit, lean setups, London-based, available across the UK and Europe.`;

// src/lib/mcp/tools/list-projects.ts
var list_projects_default = defineTool({
  name: "list_projects",
  title: "List portfolio projects",
  description: "List projects from Bohdan Rohulskyi's cinematography portfolio. Optionally filter by category (Fashion, Commercial, Documentary, Music Video).",
  inputSchema: {
    category: z.enum(CATEGORIES).optional().describe("Optional category filter: Fashion, Commercial, Documentary, or Music Video.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ category }) => {
    const items = PROJECTS.filter((p) => !category || p.filterGroup === category).map((p) => ({
      title: p.title,
      client: p.client,
      category: p.category,
      filterGroup: p.filterGroup,
      url: SITE_URL + p.url
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(items, null, 2) }],
      structuredContent: { count: items.length, projects: items }
    };
  }
});

// src/lib/mcp/tools/get-project.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z2 } from "npm:zod@^3.25.76";
var get_project_default = defineTool2({
  name: "get_project",
  title: "Get project details",
  description: "Get details for one portfolio project by its slug (the last segment of its /work/ URL, e.g. 'valentin-day').",
  inputSchema: {
    slug: z2.string().min(1).describe("Project slug, e.g. 'valentin-day' or 'kotex-arts-missing-period'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ slug }) => {
    const normalized = slug.trim().replace(/^\/?work\//, "").replace(/^\/+|\/+$/g, "");
    const project = PROJECTS.find((p) => p.url === `/work/${normalized}`);
    if (!project) {
      return {
        content: [{ type: "text", text: `No project found for slug "${normalized}".` }],
        isError: true
      };
    }
    const result = {
      title: project.title,
      client: project.client,
      category: project.category,
      filterGroup: project.filterGroup,
      url: SITE_URL + project.url,
      vimeoUrl: project.vimeoId ? `https://vimeo.com/${project.vimeoId}` : void 0,
      youtubeUrl: project.youtubeId ? `https://www.youtube.com/watch?v=${project.youtubeId}` : void 0
    };
    return {
      content: [{ type: "text", text: JSON.stringify(result, null, 2) }],
      structuredContent: result
    };
  }
});

// src/lib/mcp/tools/list-categories.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
var list_categories_default = defineTool3({
  name: "list_categories",
  title: "List portfolio categories",
  description: "List the categories used to group portfolio projects, with the number of projects in each.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const counts = CATEGORIES.map((c) => ({
      category: c,
      count: PROJECTS.filter((p) => p.filterGroup === c).length
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(counts, null, 2) }],
      structuredContent: { categories: counts }
    };
  }
});

// src/lib/mcp/tools/get-contact-info.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.23.0";
var get_contact_info_default = defineTool4({
  name: "get_contact_info",
  title: "Get contact info",
  description: "Get Bohdan Rohulskyi's public contact information, role, location and short bio.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const payload = { ...CONTACT, bio: BIO };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "bohdan-rohulskyi-mcp",
  title: "Bohdan Rohulskyi \u2014 Portfolio MCP",
  version: "0.1.0",
  instructions: "Public tools for Bohdan Rohulskyi's cinematography portfolio. Use `list_categories` to see groupings, `list_projects` (optionally filtered by category) to browse work, `get_project` for details on one project by slug, and `get_contact_info` for role, location and contact.",
  tools: [list_projects_default, get_project_default, list_categories_default, get_contact_info_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
